name: insta_assets_picker
description: An image (and videos) picker similar with Instagram, supports multi picking, crop and aspect ratio.
version: 3.1.1
repository: https://github.com/abdullahrs/insta_assets_picker_plus.git
publish_to: "none" # Remove this line if you wish to publish to pub.dev
topics:
  - picker
  - crop
  - image
  - video
  - instagram

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # insta_assets_crop: ^0.1.0 # custom package from image_crop
  insta_assets_crop:
    git:
      url: https://github.com/abdullahrs/image_crop_plus.git
      ref: main
  fraction: ^5.0.3 # to show crop ratio in crop view

  wechat_assets_picker: ^9.4.0

  # match with wechat_assets_picker package
  photo_manager: ^3.5.0
  wechat_picker_library: ^1.0.5
  extended_image: ^9.0.7
  provider: ^6.1.2
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

screenshots:
  - description: 'Scroll animation'
    path: example/screenshots/scroll.webp
  - description: 'Crop & export'
    path: example/screenshots/crop-export.webp